[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "3.11.*"
pelican = {extras = ["markdown"], version = "^4.11.0.post0"}
pelican-image-process = "^3.1.0"
